# train setting
train: False
data_dir: ''
schedule_sampler: uniform
lr: 5.0e-5
weight_decay: 0.05
bound: '-1.0,1.0'
lr_anneal_steps: 0
microbatch: -1  # -1 disables microbatches
ema_rate: 0.9999  # comma-separated list of EMA values
log_interval: 10
save_interval: 10000
resume_checkpoint: ''
use_fp16: True
fp16_scale_growth: 1.0e-3

# sample setting
clip_denoised: True
num_samples: 8
batch_size: 8
use_ddim: False
model_path: '/disk2/workspace/Rodin/log/upsamplediffusion/bound1_ts100/model080000.pt'
latent_dir: ''
low_res_path: '/disk2/workspace/Rodin/log/basediffusion/latent_sumlods_downsampled_64x64_bs8_bound1_gs1.0/140k,ts1000/samples_8x64x64x96_step140000.npz'
#low_res_path: '/disk2/datasets/triplane_data/panic/toy/LOD=4_EPOCH=20_OBJ=8/sumlod_64_xyz.npz'
progress: True

# diffusion default 
learn_sigma: True
# sigma_small: False
diffusion_steps: 100
noise_schedule: 'linear'
timestep_respacing: ''
use_kl: False
predict_xstart: False
rescale_timesteps: False
rescale_learned_sigmas: False
guidance_strength: 1.0

# model default
image_size: 256
small_size: 64
#image_size: 64
in_channels: 96
out_channels: 96
latent_dim: 512
model_channels: 192
num_res_blocks: 1
num_conv_per_resblock: 3
num_heads: 4
num_heads_upsample: -1
num_head_channels: -1
threedaware_resolutions: '64,128,256'
attention_resolutions: '32,16,8'
channel_mult: ''
dropout: 0.0
class_cond: False
use_checkpoint: False
use_scale_shift_norm: True
resblock_updown: False
use_new_attention_order: False