# train setting
train: False
data_dir: ''
schedule_sampler: uniform
lr: 1.0e-4 # 3.0e-4
weight_decay: 0.05
microbatch: -1  # -1 disables microbatches
ema_rate: 0.9999  # comma-separated list of EMA values

# sampling setting 
clip_denoised: True
num_samples: 10000
batch_size: 256 # sample batch size
use_ddim: False
#model_path: '/disk2/workspace/Rodin/log/imagediffusion_ffhq64/tmax-2024-04-05-15-59-28-889665/model020000.pt'
#model_path: '/disk2/workspace/Rodin/log/imagediffusion_ffhq64_infobatch/num_epoch200_ratio0.3_delta0.875_rescale/model017238.pt'
#model_path: '/disk2/workspace/Rodin/log/imagediffusion_ffhq64_infobatch/num_epoch200_ratio0.5_delta0.875_rescale/model014007.pt'
model_path: '/disk2/workspace/Rodin/log/imagediffusion_ffhq64_infobatch/num_epoch200_ratio0.5_delta1.0_rescale/model012905.pt'
#model_path: '/disk2/workspace/Rodin/log/imagediffusion_ffhq64_infobatch/num_epoch200_ratio0.7_delta0.875_rescale/model010554.pt'
latent_dir: ''
progress: True

# diffusion default 
learn_sigma: False
sigma_small: False
diffusion_steps: 1000
noise_schedule: 'linear'
timestep_respacing: '1000'
use_kl: False
predict_xstart: False
rescale_timesteps: False
rescale_learned_sigmas: False
guidance_strength: 1.0

# model default
image_size: 64
in_channels: 3
out_channels: 3
latent_dim: 512 #768
model_channels: 64 #192
num_res_blocks: 2 #3
num_heads: 1 #4
num_heads_upsample: -1
num_head_channels: -1 #64
attention_resolutions: '16' #'32,16,8'
channel_mult: '1,2,4,8' #''
dropout: 0.1
class_cond: False
use_checkpoint: False
use_scale_shift_norm: True
resblock_updown: True
use_fp16: True
fp16_scale_growth: 1.0e-3
use_new_attention_order: False


# classifier
#classifier_depth: 4
#classifier_width: 128
#classifier_pool: attention
#classifier_resblock_updown: True
#classifier_use_scale_shift_norm: True
#classifier_use_fp16: False
#classifier_attention_resolutions: '32,16,8'