# train setting
train: False
data_dir: ''
model_path: 'pretrained/textcondprior_lionai_ema_fp16.pth'
schedule_sampler: uniform
lr: 4.0e-5
weight_decay: 1.0e-2 #0.0
lr_anneal_steps: 0
batch_size: 64
microbatch: -1  # -1 disables microbatches
ema_rate: 0.9999  # comma-separated list of EMA values
log_interval: 10
save_interval: 10000 #10000
resume_checkpoint: ''
use_fp16: False
fp16_scale_growth: 1.0e-3

# sampling setting

# diffusion
diffusion_steps: 1000
cond_drop_prob: 0.2
loss_type: 'l2'
condition_on_text_encodings: True
cond_scale: 1.0
candidates: 2


learn_sigma: False
sigma_small: False
noise_schedule: 'linear'
timestep_respacing: ''
use_kl: False
predict_x_start: True
rescale_timesteps: False
rescale_learned_sigmas: True
guidance_strength: 0.2

# model default
embed_dim: 768
depth: 24
dim_head: 64
heads: 32
normformer: True
attn_dropout: 5.0e-2
ff_dropout: 5.0e-2
num_time_embeds: 1
num_image_embeds: 1
num_text_embeds: 1
ff_mult: 4